# Generated by Django 5.2.8 on 2025-11-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='filtered_image',
            field=models.ImageField(blank=True, null=True, upload_to='filtered/'),
        ),
    ]
