# Generated by Django 5.2.8 on 2025-12-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_photo_filtered_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='filtered_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/filtered/'),
        ),
    ]
